### ISSUE TITLE
Loading environment variables from a config file.

### ISSUE THREAD

**Issue by Natim** [loads/ailoads#1]
We should be able to tell ailoads to read some json or ini file where it could read and set environment variables.

**Comment by tarekziade** [comment]
I am not sure to see the benefit. You can read os.environ directly in the test functions. Closing as this is an old issue, feel free to reopen if you have an example

**Comment by Natim** [comment]
This is actually related to the FxA and BrowserID setup we needed for Loop.
I feel like it can be useful for other projects that needs ailoads to work with FxA authentication but we can reopen when we will need it. In the mean time you can use [fxa-client](https://github.com/mozilla/PyFxA/blob/master/fxa/__main__.py) [to export some information as env variables](https://github.com/mozilla-services/ailoads-loop/blob/master/Makefile#L24).
